### ISSUE TITLE
シリアル出力の改行コードをCRLFからLFにする

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/usb_co2#17]
- シェル上でCRLFなのかLFなのかわからないのでハマった
- トラブルを少なくするためにLFに統一したい
- `println('hoge')`を`print(`hoge\n')`になおしていくだけ

**Comment by kirisaki** [comment]
通信って CRLF に寄せるのが基本じゃなかったでしたっけ

**Comment by kirisaki** [comment]
ああ、でも CRLF だと正規表現で取り出すのがめんどっちいのか……

**Comment by urib0** [comment]
正規表現分からないのでめんどっちさが分かりませんが、LFに修正します
