### ISSUE TITLE
LEDなどの外付け部品をなくしたい

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/usb_co2#3]
- #2 の確認作業でLEDのはんだ付けしてみたら意外と手間だったのでなくしたい
- XIAOにユーザ定義LEDついてるからこれを使うことにして、基本構成では外付けLEDは無しにしたい
- 短く2連続点滅して1秒消灯（校正中） -> 点灯（校正完了） みたいな感じがよいかも

**Comment by urib0** [comment]
ソフト酒精のみ

**Comment by urib0** [comment]
とりあえず自動校正で行くのでclose
https://github.com/realglobe-Inc/usb_co2/issues/13

**Comment by urib0** [comment]
対応済み
https://github.com/realglobe-Inc/usb_co2/pull/16
