### ISSUE TITLE
校正モードにはいる操作をタクトスイッチではなくジャンパにしたい

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/usb_co2#4]
- タクトスイッチつけてみて思ったのが、「ケーブル挿すときに押さないように気をつかってしまう」
- 「スイッチ押しながらケーブル挿す」は回路屋さんだと当たり前かもしれないけど普通に高等テクだと思う
- ジャンパだと RUN <-> CALIB のような表記がシルクでできる（タクトスイッチでも press to calib とか書けるっちゃ書けるが）
- 複数個やるときの作業性はそれぞれ一短一長で大差ないかも

一方、タクトスイッチのメリットとしては、

- 校正モードにしたあと位置を戻さなくていい
- ジャンパをなくす心配がない

などでしょうかね。

**Comment by urib0** [comment]
ちょうど昨日8/3に基板の微修正を行ったので、上記も盛り込んだやつを発注しますか

**Comment by urib0** [comment]
スライドスイッチに交換

**Comment by miminashi** [comment]
@urib0 すみません今気づきました。
もしまだ未発注なら上記も含めてお願いします🙏
発注済なら次回で！

**Comment by urib0** [comment]
修正/発注/動作確認済みの為close
https://github.com/realglobe-Inc/usb_co2/pull/7
