### ISSUE TITLE
実際の校正開始まで猶予をもたせたほうがいい？

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/usb_co2#5]
- 校正開始のタイミングでCO2源（=人間）がすぐ横にいるので、実際の校正開始まで数分待ったほうがいい？
- MH-Z14Aがもともとそういう処理をしていたら必要ない
- 実験してみないとわからんけど、予防的につけておいてもいいかも

**Comment by urib0** [comment]
すでに校正モード開始から30分の猶予をもたせていますが、もう少し長くしたほうがいいですか?

**Comment by miminashi** [comment]
あ、すみません、MH-Z14Aの仕様をあんまり理解してませんでした。

https://qiita.com/urib0/items/256973f68cc1fbcd1244#0x87%E3%82%BC%E3%83%AD%E7%82%B9%E6%A0%A1%E6%AD%A3
>  400[ppm]のCO2で満たした箱等に入れるか屋外で20分以上稼働させた後にこのコマンドを送る

だから、現状の挙動で問題なさそうです。
closeします。
